name: Winex vmi-docs CI

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: 1. set environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: 2. install dep
        run: |
          rm -rf node_modules
          yarn install
          yarn run build
        env:
          CI: true

      - name: 3. script deploy
        env:
          ACCESS_TOKEN_DEPLOY: ${{secrets.VUE_DOCS_ZH_CN_TOKEN}}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
          CNAME: winex.cl.org
        run: |
          chmod +x ./scripts/deploy.sh
          bash ./scripts/deploy.sh
